# 제 4 강 데이터 구조

- 데이터의 기본 형태
- 벡터
- 행렬
- 배열

## 1. 데이터의 기본 형태

- R의 특징 중 하나는 다양한 형태의 데이터 입수와 가공이 용이하며 통계분석에 최적화된 형태의 데이터 구조를 형성한다는 점
- R에서 다루는 데이터의 기본적인 형태는 크게 벡터, 행렬, 배 열과 리스트로 나눌 수 있음

## 2. 벡터

### 1) 벡터의 생성

- 벡터는 한 개 이상의 원소로 구성된 자료구조로서 R의 자료 객체 중에서 가장 기본이 되는 자료 객체를 의미
- 하나의 벡터의 원소는 한 가지 형태(mode)만이 가능하다는 점 에 유의

seq() 함수를 이용하여 1에서 6까지 자연수로 이루 어진 벡터를 생성하기
- from=시작값, to=종료값, by=증가분(기본값)

In [1]:
seq(from=1, to=6, by=1) 

[1] 1 2 3 4 5 6

-  to=종료값, from=시작값, by=증가분

In [2]:
seq(to=6, from=1, by=1)

[1] 1 2 3 4 5 6

-  생략시 from=시작값, to=종료값, by=증가분 순서로 인식

In [3]:
seq(1, 6, 1)

[1] 1 2 3 4 5 6

seq() 함수의 조건을 지정하여 벡터를 생성

- from=시작값, to=종료값, 조건지정
- length로서 조건을 지정할 경우에는 벡터의 크기, 즉 원소의 개수를 지정하여 시작값과 종료값 사이를 등간격으로 나누어 벡터를 생성

In [4]:
seq(from=1, to=7, length=3)

[1] 1 4 7

- from=시작값, by=증가분, 조건지정
- along으로 수열을 지정하게 되면 해당 수열에 따라 동일한 크기의 벡터를 생성

In [5]:
seq(from=1, by=0.05, along=1:5)

[1] 1.00 1.05 1.10 1.15 1.20

- from=시작값, to=종료값, 조건지정

In [6]:
seq(from=1, to= 5, along=1:6)

[1] 1.0 1.8 2.6 3.4 4.2 5.0

###  2) 벡터의 기본함수

c()함수를 이용하여 기본벡터를 생성한 뒤 rep() 함 수를 이용하여 생성된 벡터의 일정 원소가 반복되는 벡터를 생성

- 1과 2로 구성된 벡터를 2회 반복

In [7]:
rep(c(1,2), times=2)

[1] 1 2 1 2

- 1:2 1에서 2까지로 구성된 벡터를 2회 반복

In [8]:
rep(1:2, times=2)

[1] 1 2 1 2

- 앞의 원소는 2회, 위의 원소는 1회 반복

In [9]:
rep(c(2,4), times=c(2,1))

[1] 2 2 4

- 앞, 뒤 모든 원소를 2회 반복

In [10]:
rep(c(2,4), each=2)

[1] 2 2 4 4

- 2, 4, 8로 구성된 벡터를 반복하되 생성되는 벡터의 크기를 5로 한정

In [11]:
rep(c(2,4,8), length=5)

[1] 2 4 8 2 4

c()함수를 이용하여 1에서 6까지 자연수로 이루어진 벡터 생성

- c() 함수 내에 입력된 값을 조합하여 벡터 생성

In [12]:
c(1,2,3,4,5,6)

[1] 1 2 3 4 5 6

- c() 함수 내 수열 값을 입력하여 벡터생성

In [13]:
c(1:6)

[1] 1 2 3 4 5 6

- 순서 임의로 지정 가능

In [14]:
c(1,3,2,4,6)

[1] 1 3 2 4 6

c()함수를 이용하여 “1”, “KNOU”, “한국방송통신대 학교”로 이루어진 문자형 벡터를 생성

- 문자형 벡터 생성시에는 따옴표(“”)가 필수적으로 추가
- c("1" , "KNOU"  , "한국방송통신대학교")

In [ ]:
c("1" , "KNOU"  , "한글안돼")

c()함수를 이용하여 논리형 벡터를 생성

In [1]:
c(T,F,T)

[1]  TRUE FALSE  TRUE

In [2]:
c(TRUE,FALSE,TRUE)

[1]  TRUE FALSE  TRUE

### 3) 벡터자료의 편집

- 벡터와 관련된 기본함수를 통해 벡터를 생성하였다면, 때에 따라서는 이를 적당히 편집하고 가공할 필요
- 자료의 삽입, 삭제 등과 관련된 방법들의 예
    - [ ]를 이용하여 벡터의 일부 원소를 추출
    - replace() 함수를 이용하여 일부 자료를 대체
    - append() 함수를 이용하여 조건에 따른 위치에 자료를 삽입
    - sort() 함수를 이용하여 자료를 정렬
    - rank() 함수를 이용하여 자료의 순위를 출력
    - order() 함수를 이용하여 오름차순에 의한 자료의 위치 값 출력


- 함수의 문법
    - 벡터명[원소번호 또는 조건문, …]
    - replace(벡터, 원소번호, 교체자료)
    - append(벡터, 삽입자료, after=원소번호)
    - sort(벡터, decreasing=FALSE, …)
    - rank(벡터, na.last = TRUE, ties.method = c("average", "first", "random", "max", "min"))
    - order(벡터, na.last = TRUE, decreasing=FALSE)


- "na.last = TRUE"라고 기본값으로 지정된 옵션의 의미는 만약 결측치가 존재한다면 이러한 결측치 값들을 자료의 맨 끝에 위치하는 것으로 간주한다는 의미
- "decreasing = FALSE"라는 기본 옵션은 내림차순이 아니라 는, 즉 오름차순을 기본값으로 한다는 의미

11에서 20까지의 값을 갖는 벡터 v1을 생성하고 세 번째와 다섯 번째 값을 추출하기

v1의 원소 중 15보다 큰 값만을 출력하고 v1중 두 번째와 네 번째 값만을 삭제하고 출력해 보기

In [4]:
v1<-c(11:20)
v1
v1[c(3,5)]

[1] 11 12 13 14 15 16 17 18 19 20

[1] 13 15

In [5]:
v1[v1>15]

[1] 16 17 18 19 20

In [6]:
v1[c(-2,-4)]

[1] 11 13 15 16 17 18 19 20

1에서 5까지의 값을 갖는 벡터 v2를 생성하고 replace() 함수를 이용하여 v2의 두 번째 원소를 6으로 바꾸어 출력

append() 함수를 이용하여 v2의 다섯 번째 자료 다음 에 8을 삽입하여 출력

In [7]:
v2 <- c(1:5)
v2

[1] 1 2 3 4 5

In [8]:
replace(v2,2,6)

[1] 1 6 3 4 5

In [9]:
append(v2,8,after=5)

[1] 1 2 3 4 5 8

In [10]:
v3 <- append(v2,8,after=5)
v3

[1] 1 2 3 4 5 8

1을 세 번 반복한 뒤 1에서 5까지 2만큼의 증가분으로 수열을 생성하여 덧붙임. 이어서 rev() 함수를 이용해 1에서 5까지 이르는 크기 3인 벡터의 역순을 구해 연결하고 2를 세 번 반복한 벡터를 덧붙임하여 데이터를 생성

sort() 함수를 이용하여 오름차순으로 정렬

rank() 함수를 통해 자 료의 순위를 출력

order() 함수를 이용하여 오름차순에 의 한 자료의 위치 값을 출력

In [11]:
x<-c(rep(1,3),seq(1,5,by=2),rev(seq(1,5,length=3)),rep(2,3))
x

[1] 1 1 1 1 3 5 5 3 1 2 2 2

In [12]:
sort(x)

[1] 1 1 1 1 1 2 2 2 3 3 5 5

In [13]:
rank(x)

[1]  3.0  3.0  3.0  3.0  9.5 11.5 11.5  9.5  3.0  7.0  7.0  7.0

In [14]:
order(x)

[1]  1  2  3  4  9 10 11 12  5  8  6  7

## 3. 행렬

- 행렬은 동일한 형태로 구성된 2차원의 데이터 구조
- 행의 차원과 열의 차원을 갖고 있으며 벡터와 마찬가지로 하나의 행렬은 수치형, 문자형, 논리형 중 한 가지 형태의 원소만 갖는 점에 유의

matrix() 함수를 이용하여 1에서 9까지의 원소를 갖는 3행 3열의 행렬을 생성하고 각 행과 열의 이름을 row 1, row 2, row 3, col 1, col 2, col 3로 지정한 뒤 출력

In [16]:
matr <- matrix(1:9, nrow=3)
dimnames(matr) <- list(paste("row", c(1:3)), paste("col", c(1:3)))
matr

col 1 col 2 col 3
row 1     1     4     7
row 2     2     5     8
row 3     3     6     9

In [17]:
length(matr)

[1] 9

In [18]:
mode(matr)

[1] "numeric"

In [19]:
dim(matr)

[1] 3 3

### 1) 행렬의 생성

행렬을 생성하는 간단한 몇 가지 기본함수
    - matrix() 함수를 이용하여 직접 생성
    - cbind() 함수를 이용하여 벡터를 병합
    - rbind() 함수를 이용하여 벡터를 병합
    - dim() 함수를 이용하여 차원(행과 열의 개수)을 직접 지정
    
문법
    - matrix(data, nrow=, ncol=, byrow=FALSE, dimnames = NULL)
    - cbind(벡터1, 벡터2, …) 또는 rbind(벡터1, 벡터2, …)
    - dim(x) <- c(행의 개수, 열의 개수)
    
    
보기 3-11에서 matrix() 함수를 이용하여 생성된 행렬 과 동일한 형태의 행렬을 rbind(), cbind(), dim() 함수를 이용하여 만들기

In [23]:
r1 <- c(1,4,7)
r2 <- c(2,5,8)
r3 <- c(3,6,9)

In [24]:
rbind(r1, r2, r3)

[,1] [,2] [,3]
r1    1    4    7
r2    2    5    8
r3    3    6    9

In [26]:
c1 <- 1:3
c2 <- 4:6
c3 <- 7:9

In [27]:
cbind(c1, c2, c3)

c1 c2 c3
[1,]  1  4  7
[2,]  2  5  8
[3,]  3  6  9

In [28]:
m1 <- 1:9
dim(m1) <- c(3,3)
m1

[,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

### 2) 행렬의 연산

- 벡터와 마찬가지로 행렬의 경우에도 자료의 삽입, 삭제, 행 또는 열의 연산 등과 관련된 다양한 방법들이 존재
- 몇 가지 주요 함수의 예를 들면 아래와 같음
    - [ ]를 이용하여 행렬의 일부 원소를 추출
    - apply() 함수를 이용한 행 또는 열의 연산
    - sweep() 함수를 이용한 행 또는 열의 연산
    
-문법
    - 행렬명[원소번호 또는 조건문, …]
    - apply(행렬, 조건 (1은 행, 2는 열, c(1,2)는 행과 열), FUN, …)
    - sweep(행렬, 조건 (1은 행, 2는 열, c(1,2)는 행과 열), STATS, FUN = “-”, …)
    
    
1에서 9까지의 원소를 갖는 행 기준의 3행 3열 행렬을 만들고 특정 행과 열, 조건에 따른 원소 추출들을 실행하고 apply()와 sweep() 함수를 통한 행 또는 열 연산을 실시

In [29]:
mat <- matrix(c(1,2,3,4,5,6,7,8,9), ncol=3, byrow=T)
mat

[,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

In [30]:
mat[1,]

[1] 1 2 3

In [31]:
mat[,3]

[1] 3 6 9

In [32]:
mat[mat[,3] > 4, 2]

[1] 5 8

In [33]:
mat[2,3]

[1] 6

apply() 함수

In [36]:
Height <- c(140,155,142,175)
size.1 <- matrix(c(130,26,110,24,118,25,112,25), ncol=2, byrow=T,  
                 dimnames=list(c("Lee", "Kim", "Park", "Choi"), c("Weight", "Waist")))

In [37]:
size <- cbind(size.1, Height)
size

Weight Waist Height
Lee     130    26    140
Kim     110    24    155
Park    118    25    142
Choi    112    25    175

In [39]:
colmean <- apply(size, 2, mean)
colmean

Weight  Waist Height 
 117.5   25.0  153.0

In [41]:
rowmean <- apply(size, 1, mean)
rowmean

Lee       Kim      Park      Choi 
 98.66667  96.33333  95.00000 104.00000

In [42]:
colvar <- apply(size, 2, var)
colvar

Weight       Waist      Height 
 81.0000000   0.6666667 259.3333333

In [43]:
rowvar <- apply(size, 1, var)
rowvar

Lee      Kim     Park     Choi 
3985.333 4430.333 3819.000 5673.000

## 4. 배열