# 5장 프로그램 구조

In [1]:
1+2

[1] 3

In [3]:
x <- 3
y <- 2
x+y

[1] 5

In [6]:
vec1 <- c(1,3)
vec2 <- c(2,4)
vec1 + vec2

[1] 3 7

In [8]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)
a+b

[,1] [,2]
[1,]    8    7
[2,]   14    7

In [9]:
4-2

[1] 2

In [10]:
x <- 5
y <- 2
x-y

[1] 3

In [12]:
vec1 <- c(4,3)
vec2 <- c(2,1)
vec1 - vec2

[1] 2 2

In [16]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)
a - b

[,1] [,2]
[1,]    2   -3
[2,]    6   -5

In [17]:
2*5

[1] 10

In [18]:
x <- 4
y <- 3
x*y

[1] 12

In [20]:
vec1 <- c(2,3)
vec2 <- c(4,5)
vec1 * vec2

[1]  8 15

In [22]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)

a*b

[,1] [,2]
[1,]   15   10
[2,]   40    6

In [23]:
10/5

[1] 2

In [24]:
x <- 4

In [26]:
y <- 2

In [27]:
x/y

[1] 2

In [30]:
vec1 <- c(6,4)
vec2 <- c(2,2)
vec1/vec2

[1] 3 2

In [32]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)
a/b


[,1]      [,2]
[1,] 1.666667 0.4000000
[2,] 2.500000 0.1666667

In [33]:
2^3

[1] 8

In [34]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(2,2,2,2),ncol=2)
a^b

[,1] [,2]
[1,]   25    4
[2,]  100    1

In [3]:
x <- 3
y <- 2
x%/%y

[1] 1

In [36]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)
a%/%b

[,1] [,2]
[1,]    1    0
[2,]    2    0

In [1]:
a <- matrix(c(5,10,2,1),ncol=2)
b <- matrix(c(3,4,5,6),ncol=2)
a
b
a%*%b


[,1] [,2]
[1,]    5    2
[2,]   10    1

[,1] [,2]
[1,]    3    5
[2,]    4    6

[,1] [,2]
[1,]   23   37
[2,]   34   56

In [39]:
1==2

[1] FALSE

In [40]:
x <- 2
y <- 3
x == y

[1] FALSE

In [41]:
1!=2

[1] TRUE

In [42]:
x <- 2
y <- 3
x != y

[1] TRUE

In [43]:
1<=2


[1] TRUE

In [44]:
x <- 2
y <- 3
x <= y

[1] TRUE

In [45]:
x <- 2
y <- 3
x >= y

[1] FALSE

In [46]:
2==2 && 3>4

[1] FALSE

In [47]:
3==3 && 3>2

[1] TRUE

## &와 &&의 차이점
 > - &&는 스칼라 자료구조의 논리연산자이고, &은 벡터를 대상으로 한 논리연산자임
 > - ||와 |도 동일한 차이임

In [12]:
2==2 & c(3>4,2==2)

[1] FALSE  TRUE

In [49]:
2==2  & c(2==2,3>4)

[1]  TRUE FALSE

In [50]:
2==2 || 3>4

[1] TRUE

In [51]:
2 != 3 || 3>2 

[1] TRUE

In [53]:
2!=2 || c(2==2,3>4)

[1] TRUE

In [54]:
2!=2 | c(2==2,3>4)

[1]  TRUE FALSE

# 집합연산자


In [56]:
x <- c(1,2,5)
y <- c(5,1,8,9)
intersect(x,y)

[1] 1 5

In [57]:
union(x,y)

[1] 1 2 5 8 9

In [59]:
setdiff(x,y)

[1] 2

In [60]:
setdiff(y,x)

[1] 8 9

In [61]:
setequal(x,y)

[1] FALSE

In [62]:
setequal(x,c(1,2,5))

[1] TRUE

In [63]:
2%in%x

[1] TRUE

In [64]:
2%in%y

[1] FALSE

In [13]:
choose(10,2)

[1] 45

> choose함수는 아래수식임
\begin{equation*}
{n \choose k} = \frac{n!}{k!(n-k)!} 
\end{equation*}

In [9]:
pi

[1] 3.141593

In [27]:
options(digits=2)


print(pi)

[1] 3.1


In [28]:
log(2)


[1] 0.69

In [18]:
exp(0.693147180559945)

[1] 1.9999999999999993

In [20]:
sqrt(4)

[1] 2

-----------
# 프로그래밍 구조
-----------------
   

In [24]:
x <- c(1,2,3,4)
y <- c(2,1,4,5)
if(sum(x) < sum(y)) print(x)

[1] 1 2 3 4


In [25]:
if(sum(x) < sum(y)){
    print(mean(x))
    print(var(x))
}
    

[1] 2.5
[1] 1.6666666666666667


In [30]:
if(mean(x) > mean(y)){
    print(mean(x))
    print(var(x))
}else{
    print(mean(y))
    print(var(y))
}

[1] 3
[1] 3.3333333333333335


In [32]:
type <- "var"
switch(type, mean=mean(x),median=median(x),sum=sum(x), var= var(x))

[1] 1.6666666666666667

In [33]:
switch(1,mean(x),sum(x),var(x))

[1] 2.5

In [29]:
for(i in 1:5){
       print(i)
    # print(rep(i,i))
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [36]:
x <- 0
for(i in 1:10){
    x <- x+i
}
x   

[1] 55

In [ ]:
i <- 1
while(i<=100){
    print(rep(i,i))
    i <- i+1
}

In [38]:
i <- 1
x <- 0
while(i<=10){
    x <- x + i
    i <- i + 1
}

x


[1] 55

In [39]:
i <- 1

repeat{
    if(i>5) break
    
    print(rep(i,i))
    i <- i+1
}


[1] 1
[1] 2 2
[1] 3 3 3
[1] 4 4 4 4
[1] 5 5 5 5 5


In [43]:
i <- 1
x <- 0

repeat{
    if(i>10) break
        
        x <- x+i
        i <- i+1
}

x

[1] 55

In [47]:
x <- 0
for(i in 1:10){
    x <- x + i
    if(x>25) break
    print(x)
}

[1] 1
[1] 3
[1] 6
[1] 10
[1] 15
[1] 21


In [49]:
i <- 1
x <- 0

while(i<10){
    i <- i+1
    if(i < 8)
        next
    -----------------------
    print(i)
    
    x <- x+i
}

[1] 8
[1] 9
[1] 10
